### ISSUE TITLE
hwmondata.sh change for Buster

### ISSUE THREAD

**Issue by subtrEM** [rwbl/domoticz-homeautomation-workbook#1]
With hwmondata.sh (20190619), the upgrade to Raspbian Buster causes a JSON parsing failure:
'free -h' reports memory in "Mi" units, as opposed to the expected "M".
Possible workaround: -> in 'tr -d', filter out _all_ alphabetical characters, not just M
```
# RAM free
ramfree=$(free -h | head -n2 | tail -n1 | awk '{print $4}' | tr -d [:alpha:])
# RAM used
ramused=$(free -h | head -n2 | tail -n1 | awk '{print $3}' | tr -d [:alpha:])
```

**Comment by rwbl** [comment]
Thanks for the info and the workaround.
Updated the Bash script in workbook v20200318 zip file hardware_monitor.zip.
Sorry for late reply - been busy working on new version of the workbook.

**Comment by subtrEM** [comment]
Looks like there's another catch: with the RPi4 with larger memory, sizes are being reported in GiB beside MiB units,
You might be better off with the -m parameter rather than -h - will round off very small sizes of memory < 1 MiB, but the user will have other worries when memory goes down that low :-)

**Comment by rwbl** [comment]
Thanks for pointing out. Will be updated in the next version. 
Appreciated.
